---
- name: transfer temlates file to remote server.
  template: 
    src: nginxrepo.j2
    dest: /etc/yum.repos.d/nginx.repo

- name: install nginx web service.
  yum: 
    name: nginx
    state: latest

- name: configure nginx service config file.
  template:
    src: nginxconf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify:
    - start nginx service

- name: setting web service index page.
  template:
    src: index.j2
    dest: /usr/share/nginx/html/index.php
